name: tactile_ssl
channels: 
 - pytorch
 - xformers
 - nvidia
 - conda-forge 
dependencies:
 - python=3.9
 - pytorch=2.0.*
 - pytorch-cuda=11.8
 - torchvision
 - lightning=2.0.*
 - xformers
 - hydra-core
 - hydra-colorlog
 - wandb
 - matplotlib
 - einops
 - tqdm
 - scipy
 - scikit-learn
 - opencv
 - h5py
 - rich
 - pip
 - pip:
    - rootutils
    - pre-commit
    - ikpy
    - gdown==5.1.0
