#@package _global_

task_name: t1_force
ssl_model_size: base
train_data_budget: 1.0
val_data_budget: 1.0
experiment_name: ${sensor}_${task_name}_${ssl_name}_vit${ssl_model_size}_${train_data_budget}
seed: 42


hydra:
  job:
    id: ${now:%Y.%m.%d}_${now:%H-%M}
  run:
    dir: ${paths.log_dir}/${hydra.job.id}_${experiment_name}
    
wandb:
  project: ${task_name}_${sensor}
  group: ~
  tags: ["${ssl_name}"]

trainer:
  max_epochs: 51
  validation_frequency: 5
  sanity_validate: true
  save_checkpoint_dir: ${paths.output_dir}/checkpoints
  checkpoint_interval_type: 'log'
  max_task_checkpoints: 10
  save_probe_weights_only: True

data:
  train_data_budget: ${train_data_budget}
  val_data_budget: ${val_data_budget}

test:
  data:
    dataset_name: ["flat/batch_1"]
    batch_size: 200
  tester:
    _partial_: True
    _target_: tactile_ssl.test.TestForceSL
  path_outputs: ${paths.tacbench_dir}/${task_name}_${sensor}/

task:
  _target_: tactile_ssl.downstream_task.ForceSLModule
  checkpoint_task: ~

  model_encoder:
    _target_: tactile_ssl.model.vit_${ssl_model_size}
    img_size: ${data.dataset.config.transforms.resize}
    in_chans: 6
    pos_embed_fn: sinusoidal
    num_register_tokens: 1

  model_task:
    _target_: tactile_ssl.downstream_task.ForceLinearProbe
    embed_dim: ${ssl_model_size}
    num_heads: 12
    depth: 1
    with_last_activations: true

  checkpoint_encoder: ${paths.encoder_checkpoint_root}/${ssl_name}_vit${ssl_model_size}.ckpt
  train_encoder: false
  encoder_type: ${ssl_name}

  optim_cfg:
    _partial_: True
    _target_: torch.optim.Adam
    lr: 0.0001

  scheduler_cfg: ~
